pool:
  vmImage: ubuntu-18.04
  container: mcr.microsoft.com/dotnet/sdk:6.0


stages:
 - stage: continuous_integration
   displayName: Continious Integration
   jobs:
   - job: build
     displayName: Build
     steps:
     - script: dotnet --version
       displayName: Check .NET Version
     - script: dotnet restore
       displayName: Restore NuGet Packages
     - script: dotnet build
       displayName: Build .NET Project
     - script: dotnet run
       displayName: Run .NET Project
       - task: ArchiveFiles@2
         inputs:
           rootFolderOrFile: '$(Build.BinariesDirectory)'
           includeRootFolder: true
           archiveType: 'zip'
           archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
           replaceExistingArchive: true
