pool:
  vmImage: ubuntu-18.04
  container: mcr.microsoft.com/dotnet/sdk:6.0


stages:
 - stage: continuous_integration
   displayName: Continious Integration
   jobs:
   - job: build
     displayName: Build
     steps:
     - script: dotnet --version
       displayName: Check .NET Version
     - script: dotnet restore
       displayName: Restore NuGet Packages
     - script: dotnet build
       displayName: Build .NET Project
     - script: dotnet run
       displayName: Run .NET Project
<<<<<<< HEAD
     - publish: $(System.DefaultWorkingDirectory)/bin/WebApp
        displayName: Publish Artifacts
        artifact: WebApp
=======
   
>>>>>>> 38c6ffb6866ee1c8b6977f466bcfa6c2cbc0e5ec
